-- OpenEMR Patient Data table refactored for PostgreSQL
-- https://github.com/openemr/openemr/blob/master/sql/database.sql

CREATE TABLE patient_data (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE DEFAULT NULL,
  "title" varchar(255) NOT NULL default '',
  "language" varchar(255) NOT NULL default '',
  "financial" varchar(255) NOT NULL default '',
  "fname" varchar(255) NOT NULL default '',
  "lname" varchar(255) NOT NULL default '',
  "mname" varchar(255) NOT NULL default '',
  "DOB" date default NULL,
  "street" varchar(255) NOT NULL default '',
  "postal_code" varchar(255) NOT NULL default '',
  "city" varchar(255) NOT NULL default '',
  "state" varchar(255) NOT NULL default '',
  "country_code" varchar(255) NOT NULL default '',
  "drivers_license" varchar(255) NOT NULL default '',
  "ss" varchar(255) NOT NULL default '',
  "occupation" text,
  "phone_home" varchar(255) NOT NULL default '',
  "phone_biz" varchar(255) NOT NULL default '',
  "phone_contact" varchar(255) NOT NULL default '',
  "phone_cell" varchar(255) NOT NULL default '',
  "pharmacy_id" int NOT NULL default '0',
  "status" varchar(255) NOT NULL default '',
  "contact_relationship" varchar(255) NOT NULL default '',
  "date" timestamp default NULL,
  "sex" varchar(255) NOT NULL default '',
  "referrer" varchar(255) NOT NULL default '',
  "referrerID" varchar(255) NOT NULL default '',
  "providerID" int default NULL,
  "ref_providerID" int default NULL,
  "email" varchar(255) NOT NULL default '',
  "email_direct" varchar(255) NOT NULL default '',
  "ethnoracial" varchar(255) NOT NULL default '',
  "race" varchar(255) NOT NULL default '',
  "ethnicity" varchar(255) NOT NULL default '',
  "religion" varchar(40) NOT NULL default '',
  "interpretter" varchar(255) NOT NULL default '',
  "migrantseasonal" varchar(255) NOT NULL default '',
  "family_size" varchar(255) NOT NULL default '',
  "monthly_income" varchar(255) NOT NULL default '',
  "billing_note" text,
  "homeless" varchar(255) NOT NULL default '',
  "financial_review" timestamp default NULL,
  "pubpid" varchar(255) NOT NULL default '',
  "pid" SERIAL UNIQUE NOT NULL,
  "genericname1" varchar(255) NOT NULL default '',
  "genericval1" varchar(255) NOT NULL default '',
  "genericname2" varchar(255) NOT NULL default '',
  "genericval2" varchar(255) NOT NULL default '',
  "hipaa_mail" varchar(3) NOT NULL default '',
  "hipaa_voice" varchar(3) NOT NULL default '',
  "hipaa_notice" varchar(3) NOT NULL default '',
  "hipaa_message" varchar(20) NOT NULL default '',
  "hipaa_allowsms" VARCHAR(3) NOT NULL DEFAULT 'NO',
  "hipaa_allowemail" VARCHAR(3) NOT NULL DEFAULT 'NO',
  "squad" varchar(32) NOT NULL default '',
  "fitness" int NOT NULL default '0',
  "referral_source" varchar(30) NOT NULL default '',
  "usertext1" varchar(255) NOT NULL DEFAULT '',
  "usertext2" varchar(255) NOT NULL DEFAULT '',
  "usertext3" varchar(255) NOT NULL DEFAULT '',
  "usertext4" varchar(255) NOT NULL DEFAULT '',
  "usertext5" varchar(255) NOT NULL DEFAULT '',
  "usertext6" varchar(255) NOT NULL DEFAULT '',
  "usertext7" varchar(255) NOT NULL DEFAULT '',
  "usertext8" varchar(255) NOT NULL DEFAULT '',
  "userlist1" varchar(255) NOT NULL DEFAULT '',
  "userlist2" varchar(255) NOT NULL DEFAULT '',
  "userlist3" varchar(255) NOT NULL DEFAULT '',
  "userlist4" varchar(255) NOT NULL DEFAULT '',
  "userlist5" varchar(255) NOT NULL DEFAULT '',
  "userlist6" varchar(255) NOT NULL DEFAULT '',
  "userlist7" varchar(255) NOT NULL DEFAULT '',
  "pricelevel" varchar(255) NOT NULL default 'standard',
  "regdate"     date DEFAULT NULL,
  "contrastart" date DEFAULT NULL,
  "completed_ad" VARCHAR(3) NOT NULL DEFAULT 'NO',
  "ad_reviewed" date DEFAULT NULL,
  "vfc" varchar(255) NOT NULL DEFAULT '',
  "mothersname" varchar(255) NOT NULL DEFAULT '',
  "guardiansname" text,
  "allow_imm_reg_use" varchar(255) NOT NULL DEFAULT '',
  "allow_imm_info_share" varchar(255) NOT NULL DEFAULT '',
  "allow_health_info_ex" varchar(255) NOT NULL DEFAULT '',
  "allow_patient_portal" varchar(31) NOT NULL DEFAULT '',
  "deceased_date" timestamp default NULL,
  "deceased_reason" varchar(255) NOT NULL default '',
  "soap_import_status" int DEFAULT NULL,
  "cmsportal_login" varchar(60) NOT NULL default '',
  "care_team_provider" text,
  "care_team_facility" text,
  "care_team_status" text,
  "county" varchar(40) NOT NULL default '',
  "industry" text,
  "imm_reg_status" text,
  "imm_reg_stat_effdate" text,
  "publicity_code" text,
  "publ_code_eff_date" text,
  "protect_indicator" text,
  "prot_indi_effdate" text,
  "guardianrelationship" text,
  "guardiansex" text,
  "guardianaddress" text,
  "guardiancity" text,
  "guardianstate" text,
  "guardianpostalcode" text,
  "guardiancountry" text,
  "guardianphone" text,
  "guardianworkphone" text,
  "guardianemail" text,
  "sexual_orientation" text,
  "gender_identity" text,
  "birth_fname" text,
  "birth_lname" text,
  "birth_mname" text,
  "dupscore" int NOT NULL default -9,
  "name_history" text,
  "suffix" text,
  "street_line_2" text,
  "patient_groups" text,
  "prevent_portal_apps" text
);

ALTER SEQUENCE patient_data_pid_seq RESTART WITH 1000;